### PR TITLE
Start adding some lexers.

### PR DESCRIPTION
**Pull request by ralphbean**
These will be used by fedora-hubs.

### CODE REVIEW

**Comment by pypingou** [comment]
Cool :+1:

**Comment by pypingou** [comment]
Does it add a new dependency?

**Comment by ralphbean** [comment]
> Does it add a new dependency?

I want to make them optional, so that people don't have to install the whole pygments stack everywhere.

**Comment by ralphbean** [comment]
Silly me, fedmsg already depends on pygments.

**Comment by ralphbean** [comment]
FYI, review request in here:  https://bugzilla.redhat.com/show_bug.cgi?id=1318781

**Pull request merged**
