### PR TITLE
Protect ourselves from lists.

### PR DESCRIPTION
**Pull request by ralphbean**

### CODE REVIEW

**Comment by pypingou** [comment]
:+1: (or do we want to iterate through the component of the list? I guess they are coming from conglomerate no?)

**Comment by ralphbean** [comment]
> (or do we want to iterate through the component of the list? I guess they are coming from conglomerate no?)

No, they are weird koji internal stuff.  In this case, specific to the ``createImage`` task.

**Comment by ralphbean** [comment]
> they are weird koji internal stuff

I'd add that we likely started hitting this due to a new release of koji that was added to the repos(?)

**Comment by pypingou** [comment]
ok thanks for the explanations

**Pull request merged**
