### PR TITLE
Fix #96  "in advance of" should read "newer than"

### LINKED ISSUE #96: Use msg2long_form api for bodhi backend stuff
We would use it for bodhi when the masher finishes in order to generate a big templated email.

We could use mako templates for it behind the scenes.

### PR DESCRIPTION
**Pull request by vhalli**

### CODE REVIEW

**Comment by pypingou** [comment]
:+1: for the change but I expect this will require an adjustment to the unit-test suite as well :)

**Comment by inheritedburrp** [comment]
@pypingou yes working on it.

**Comment by inheritedburrp** [comment]
it seems that the build is failing for some other reason.

**Comment by pypingou** [comment]
I'm a little confused here, @vhalli opened the pull-request but with the commits from @inheritedburrp ?

**Comment by inheritedburrp** [comment]
We had dev Sprint, and I had some issues with my laptop. Is the PR all ok?

**Comment by pypingou** [comment]
On Sun, Jul 26, 2015 at 10:09:11AM -0700, Anuj Sharma wrote:
>    We had dev Sprint, and I had some issues with my laptop. Is the PR all ok?

Code wise it looks fine, I just wanted to test it locally before merging and see
if I could reproduce/fix the issue seen on travis.
I'll let you know once I did this (which might be on Tuesday, unless someone
beats me to it)

**Comment by ralphbean** [comment]
Looks good here.  :)  Thanks!

**Pull request merged**
