### PR TITLE
fedmsg.meta processor for MBS.

### LINKED ISSUE #415: Write a processor for the MBS
The module build service is coming together.  We need to write a fedmsg_meta processor for its messages.

Here's an example:  https://apps.stg.fedoraproject.org/datagrepper/id?id=2017-859a8cfb-6d95-43f4-9c0b-897e833b06b5&is_raw=true&size=extra-large

### PR DESCRIPTION
**Pull request by ralphbean**
This fixes #415.

We still need a modularity icon.  @asamalik should have one for us soon.

### CODE REVIEW

**Comment by ralphbean** [comment]
(p.s., tests here won't pass until #416 is merged..)

**Comment by ralphbean** [comment]
Rebased so that travis should be happy.

This is ready to merge/ready for review from my PoV.

**Comment by pypingou** [comment]
Loving the simplicity :)

**Comment by pypingou** [comment]
It looks good to me, so let's merge :)

Let us know when you need this deployed

**Comment by ralphbean** [comment]
> Let us know when you need this deployed

~March 7th (alpha freeze).  :)

**Pull request merged**
