### PR TITLE
Fix pkgdb for admin actions

### PR DESCRIPTION
**Pull request by pypingou**

### CODE REVIEW

**Comment by ralphbean** [comment]
LGTM.  :)

**Comment by ralphbean** [comment]
Is there a time-table for when this needs to be released?

**Comment by pypingou** [comment]
@ralphbean when you have time but I am about to open the pull-request to merged the feature branch into master in pkgdb and we wanted to test it in stg soonish.

How much work is it for you?

**Comment by ralphbean** [comment]
> How much work is it for you?

No big deal.  ;)

**Pull request merged**
