### PR TITLE
Perform 26 smaller queries instead of 1 to retrieve the entire list of users

### PR DESCRIPTION
**Pull request by pypingou**
This actually slows down thing a little but at least it no longer runs
into time-out issues.

### CODE REVIEW

**Comment by abompard** [comment]
I suppose there is no way to page requests on the server?

**Comment by pypingou** [comment]
Unfortunately not on FAS2

**Comment by pypingou** [comment]
grmbl, wrong button :)

**Comment by abompard** [comment]
OK, :+1:

**Comment by lmacken** [comment]
:+1: Fine with me.

**Comment by ralphbean** [comment]
I added two small mostly cosmetic changes to this PR.

Let's merge it and get it out the door.

**Comment by sachinkamath** [comment]
@ralphbean  +1

Looks good to me :+1:

**Comment by ralphbean** [comment]
:)  Thanks all!

**Pull request merged**
