### PR TITLE
Correcting the displayed link for ask.stg.*

### PR DESCRIPTION
**Pull request by Metonimie**
I managed to solving my first easybug.

Please see:
https://pagure.io/fedora-infrastructure/issue/4181

### CODE REVIEW

**Comment by pypingou** [comment]
Could you maybe add a test for this?

**Comment by Metonimie** [comment]
Yes. Will be done

**Comment by Metonimie** [comment]
Probably I should have created a new branch for this instead of working on develop. Can it still be done now?

**Comment by pypingou** [comment]
You could likely change now but I don't know if github allows editing the PR for this.

Two comments:
- I was thinking to add 1 test for this, not duplicate the entire test suite, this seems a little much :)
- The tests are also used for documentation in https://fedora-fedmsg.readthedocs.io/en/latest/, you can exclude them from being published there by prefixing them with ``Legacy``, so could you mark them as such?

**Comment by Metonimie** [comment]
I'd change but I'm not that experienced with github and I don't want to mess things up

**Comment by pypingou** [comment]
This looks good to me.

@ralphbean if you have the time could you give it a quick look? Does it sound like a reasonable approach?

**Comment by pypingou** [comment]
Alright, let's merge :)

**Pull request merged**
